---
apiVersion: v1
kind: Service
metadata:
  name: {{CF_REPO_NAME}}-{{NEW_PROD_SERVICE}}
  labels:
    app: {{NEW_PROD_SERVICE}}
spec:
  type: ClusterIP
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 8080
  selector:
    app: {{NEW_PROD_SERVICE}}
    tier: web

