---
apiVersion: v1
kind: Service
metadata:
  name: {{CF_REPO_NAME}}
  labels:
    app: {{CURRENT_PROD_SERVICE}}
spec:
  type: NodePort
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 8080
  selector:
    app: {{CURRENT_PROD_SERVICE}}
    tier: web

